version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: chips-development
  web:
    env_file: .development_environment_secrets.sh
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
