version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: chips-development
  web:
    build:
      context: .
      args:
        - DB_NAME
        - DB_PASSWORD
        - DB_USER_NAME
        - PORT
        - MIX_ENV
    ports:
      - "8000:8000"
    depends_on:
      - postgres
