version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: dev-password
      POSTGRES_DB: chips-development
  web:
    env_file: .development_environment_secrets.sh
    build:
      context: .
    command: bash
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - ./lib:/chips-app/lib
      - ./test:/chips-app/test
      - ./priv/static/js:/chips-app/priv/static/js
      - ./priv/repo:/chips-app/priv/repo
    working_dir: /chips-app
    depends_on:
      - postgres
