version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "5432:5432"
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chips_prod
