jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Decode gcloud key
          command: echo ${GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json

      - run:
          name: Authenticate gcloud and set appropriate zone
          command: >-
                     sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update && \
                       sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json && \
                       sudo /opt/google-cloud-sdk/bin/gcloud config set project ${GCLOUD_PROJECT} && \
                       sudo /opt/google-cloud-sdk/bin/gcloud config set compute/zone ${GCLOUD_ZONE}

      - run:
          name: Build docker image
          command: >-
                     docker build --no-cache -t ${DOCKER_IMAGE_REPOSITORY}:${CIRCLE_SHA1} .

      - run:
          name: Upload docker image to repository
          command: sudo /opt/google-cloud-sdk/bin/gcloud docker -- push ${DOCKER_IMAGE_REPOSITORY}:${CIRCLE_SHA1}

      - run:
          name: Update instance definition
          command: >-
                     sudo /opt/google-cloud-sdk/bin/gcloud beta compute instances update-container chips-${ENVIRONMENT} \
                       --container-image ${DOCKER_IMAGE_REPOSITORY}:${CIRCLE_SHA1}

